{
  "openapi": "3.1.0",
  "info": { "title": "VOLTERAS CONNECT", "version": "0.1.0" },
  "servers": [{ "url": "https://api.volteras.com/" }],
  "paths": {
    "/v1/oauth2/token": {
      "post": {
        "tags": ["Authentication"],
        "summary": "Auth Token",
        "description": "Obtain OAuth 2.0 Access Token\n\nThis endpoint follows the OAuth 2.0 industry-standard protocol for authorization.\nIt performs authorization and returns the access token and refresh token.\n\nUsage:\n    - Use `client_credentials` grant type to authenticate with `client_id` and `client_secret`.\n    - Use `refresh_token` grant type to refresh an existing token.",
        "operationId": "auth_token_v1_oauth2_token_post"
      }
    },
    "/v1/oauth2/test-token": {
      "post": {
        "tags": ["Authentication"],
        "summary": "Test Token",
        "description": "Test Access Token\n\nThis endpoint validates the access token and retrieves the associated `clientId` and `organizationId`.",
        "operationId": "test_token_v1_oauth2_test_token_post",
        "security": [{ "OAuth2ClientCredentialsBearer": [] }]
      }
    },
    "/v1/accounts": {
      "get": {
        "tags": ["Accounts"],
        "summary": "List Accounts",
        "description": "List Accounts\n\nRetrieve a paginated list of accounts associated with the current organization.\n\nThis endpoint allows you to list accounts based on the following criteria:\n\n- The accounts are associated with the current organization.\n- Pagination and sorting.\n- Only active accounts are included in the list.",
        "operationId": "list_accounts_v1_accounts_get",
        "security": [{ "OAuth2ClientCredentialsBearer": [] }]
      }
    },
    "/v1/accounts/{account_id}": {
      "get": {
        "tags": ["Accounts"],
        "summary": "Get Account",
        "description": "Retrieve account details by providing its unique identifier.\n\nParameters:\n    - account_id: The unique identifier (ID) of the account to retrieve.\n\nReturns:\n    - Detailed information about the retrieved account.\n\nNote:\n    - The 'account_id' parameter should be a valid and existing account identifier.",
        "operationId": "get_account_v1_accounts__account_id__get",
        "security": [{ "OAuth2ClientCredentialsBearer": [] }]
      }
    },
    "/v1/accounts:connect": {
      "post": {
        "tags": ["Accounts"],
        "summary": "Action Connect",
        "description": "Initiate Account Connection Flow\n\nGenerate a URL to initiate the account connection flow, which allows users to connect their accounts.\n\nAfter the connection flow is completed, the vehicle owner is redirected to the provided return URL with the following parameters:\n- `result` indicating success or failure.\n- `accountId` representing the ID of the connected account.",
        "operationId": "action_connect_v1_accounts_connect_post",
        "security": [{ "OAuth2ClientCredentialsBearer": [] }]
      }
    },
    "/v1/accounts/{account_id}:disconnect": {
      "post": {
        "tags": ["Accounts"],
        "summary": "Action Disconnect",
        "description": "Disconnect an Account\n\nDisconnect the specified account, terminating its connection.\n\nParameters:\n    - `account_id`: The unique identifier (ID) of the account to disconnect.\n\nReturns:\n    - Response: A 200 OK response indicating successful disconnection.\n\nThis endpoint allows you to disconnect an account by providing its unique 'account_id'.\nUpon successful disconnection, the account's connection is terminated.\n\nNote:\n    - The `account_id` should correspon[...]",
        "operationId": "action_disconnect_v1_accounts__account_id__disconnect_post",
        "security": [{ "OAuth2ClientCredentialsBearer": [] }]
      }
    },
    "/v1/vehicles": {
      "get": {
        "tags": ["Vehicles"],
        "summary": "List Vehicles",
        "description": "List Vehicles\n\nRetrieve a paginated list of vehicles associated with your organization.\n\nReturns:\n    - A paginated response containing a list of vehicles.\n\nThis endpoint allows you to list vehicles associated with your organization based on the following criteria:\n- Vehicles must have synchronization enabled, `is_sync_enabled`.\n\nNote:\n    - Certain fields like `vin` and `registration_plate` are excluded from the response to enhance privacy and security.",
        "operationId": "list_vehicles_v1_vehicles_get",
        "security": [{ "OAuth2ClientCredentialsBearer": [] }]
      }
    },
    "/v1/vehicles/{vehicle_id}": {
      "get": {
        "tags": ["Vehicles"],
        "summary": "Get Vehicle",
        "description": "Retrieve Vehicle by ID\n\nRetrieve detailed information about a vehicle by specifying its unique identifier (ID).\n\nReturns:\n    - A response containing detailed information about the vehicle.\n\nNote:\n- Certain sensitive fields like `vin` and `registration_plate` are excluded from the response to enhance privacy and security.",
        "operationId": "get_vehicle_v1_vehicles__vehicle_id__get",
        "security": [{ "OAuth2ClientCredentialsBearer": [] }]
      }
    },
    "/v1/vehicles/{vehicle_id}/options": {
      "get": {
        "tags": ["Vehicles"],
        "summary": "Get Vehicle Options",
        "description": "Retrieves the options data for a specific Tesla vehicle based on its ID.\n\nParameters:\n- db_session: Database session to interact with the database.\n- vehicle: The vehicle object retrieved based on the provided vehicle ID.\n\nReturns:\n- schemas.VehicleOptions: A schema containing the options data for the queried Tesla vehicle.",
        "operationId": "get_vehicle_options_v1_vehicles__vehicle_id__options_get",
        "security": [
          { "OAuth2ClientCredentialsBearer": ["vehicle:information"] }
        ]
      }
    },
    "/v1/vehicles/{vehicle_id}/registration-plate": {
      "post": {
        "tags": ["Vehicles"],
        "summary": "Update Registration Plate",
        "description": "Update Vehicle Registration Plate\n\nUpdate the registration plate of the specified vehicle.\n\nParameters:\n    - `vehicle_id`: The unique identifier (ID) of the vehicle to update.\n\nReturns:\n    - A response containing the updated vehicle information.\n\nNote:\n    - The `vehicle_id` should correspond to a valid and existing vehicle identifier.",
        "operationId": "update_registration_plate_v1_vehicles__vehicle_id__registration_plate_post",
        "security": [
          { "OAuth2ClientCredentialsBearer": ["vehicle:information"] }
        ]
      }
    },
    "/v1/vehicles/{vehicle_id}/specifications": {
      "get": {
        "tags": ["Vehicles"],
        "summary": "Get Vehicle Specifications",
        "description": "Retrieve Vehicle Specifications\n\nObtain detailed specifications for a vehicle, with current support only for Tesla vehicles.\n\nParameters:\n    - `vehicle_id`: The unique identifier (ID) of the vehicle to retrieve specifications for.\n\nReturns:\n    - Detailed specifications of the vehicle.\n\nThis endpoint allows you to retrieve comprehensive specifications for a specific vehicle identified by its unique 'vehicle_id'.\nSpecifications are currently only supported for [...]",
        "operationId": "get_vehicle_specifications_v1_vehicles__vehicle_id__specifications_get",
        "security": [
          { "OAuth2ClientCredentialsBearer": ["vehicle:information"] }
        ]
      }
    },
    "/v1/vehicles/{vehicle_id}/trim/suggestions": {
      "get": {
        "tags": ["Vehicles"],
        "summary": "Get Vehicle Trim Suggestions",
        "description": "Retrieve Trim Suggestions for a Vehicle\n\nObtain a list of trim suggestions for the specified vehicle.\n\nParameters:\n    - `vehicle_id`: The unique identifier (ID) of the vehicle to retrieve trim suggestions for.\n\nReturns:\n    - A list of trim suggestions for the vehicle.\n\nThis endpoint allows you to retrieve a list of trim suggestions for a specific vehicle identified by its unique `vehicle_id`.\nTrim suggestions are based on available data and are subject to the[...]",
        "operationId": "get_vehicle_trim_suggestions_v1_vehicles__vehicle_id__trim_suggestions_get",
        "security": [
          { "OAuth2ClientCredentialsBearer": ["vehicle:information"] }
        ]
      }
    },
    "/v1/vehicles/{vehicle_id}:disconnect": {
      "post": {
        "tags": ["Vehicles"],
        "summary": "Action Disconnect",
        "description": "Disconnect Vehicle from Organization\n\nDisconnect the specified vehicle from your organization.\nThis action stops the synchronization of the vehicle's data, rendering the vehicle inaccessible.\n\nParameters:\n    - `vehicle_id`: The unique identifier (ID) of the vehicle to disconnect.\n\nReturns:\n    - A 200 OK response indicating successful disconnection.\n\nThis endpoint allows you to disconnect a specific vehicle from your organization, ceasing the synchronization o[...]",
        "operationId": "action_disconnect_v1_vehicles__vehicle_id__disconnect_post",
        "security": [{ "OAuth2ClientCredentialsBearer": [] }]
      }
    },
    "/v1/vehicles/{vehicle_id}/trim": {
      "put": {
        "tags": ["Vehicles"],
        "summary": "Update Vehicle Trim",
        "description": "Set Vehicle Trim\n\nSet the trim for the specified vehicle.\n\nParameters:\n    - `vehicle_id`: The unique identifier (ID) of the vehicle to update the trim for.\n\nReturns:\n    - A 202 Accepted response indicating successful trim update.\n\nThis endpoint allows you to set the trim for a specific vehicle identified by its unique `vehicle_id`.\n\nNote:\n    - The `vehicle_id` should correspond to a valid and existing vehicle identifier.\n    - Trim information must be val[...]",
        "operationId": "update_vehicle_trim_v1_vehicles__vehicle_id__trim_put",
        "security": [
          { "OAuth2ClientCredentialsBearer": ["vehicle:information"] }
        ]
      }
    },
    "/v1/vehicles/{vehicle_id}/telemetry": {
      "get": {
        "tags": ["Vehicle Telemetry"],
        "summary": "Get Vehicle Telemetry",
        "description": "Retrieve Vehicle Telemetry\n\nRetrieve telemetry data for the specified vehicle. The telemetry data provides essential information about the vehicle's status and performance.\n\nParameters:\n    - `vehicle_id`: The unique identifier (ID) of the vehicle to retrieve telemetry data for.\n\nReturns:\n    - Telemetry data for the vehicle.\n\nTelemetry Information returned might include:\n- Odometer: The total distance traveled by the vehicle, recorded in kilometers. The timest[...]",
        "operationId": "get_vehicle_telemetry_v1_vehicles__vehicle_id__telemetry_get",
        "security": [
          { "OAuth2ClientCredentialsBearer": ["vehicle:telemetry"] }
        ]
      }
    },
    "/v1/vehicles/{vehicle_id}/command-executions": {
      "get": {
        "tags": ["Vehicle Command Executions"],
        "summary": "List Vehicle Command Executions",
        "description": "List the vehicle's command executions.",
        "operationId": "list_vehicle_command_executions_v1_vehicles__vehicle_id__command_executions_get",
        "security": [
          { "OAuth2ClientCredentialsBearer": [] },
          { "OAuth2ClientCredentialsBearer": ["vehicle:commands"] }
        ]
      }
    },
    "/v1/vehicles/{vehicle_id}/command-executions/{vehicle_command_execution_id}": {
      "get": {
        "tags": ["Vehicle Command Executions"],
        "summary": "Get Vehicle Command Execution",
        "description": "Get a vehicle command execution by ID.",
        "operationId": "get_vehicle_command_execution_v1_vehicles__vehicle_id__command_executions__vehicle_command_execution_id__get",
        "security": [
          { "OAuth2ClientCredentialsBearer": [] },
          { "OAuth2ClientCredentialsBearer": ["vehicle:commands"] }
        ]
      }
    },
    "/v1/vehicles/{vehicle_id}/command-execution:actuate-front-trunk": {
      "post": {
        "tags": ["Vehicle Command Executions"],
        "summary": "Action Actuate Front Trunk",
        "description": "Create a `ACTUATE_FRONT_TRUNK` command execution.",
        "operationId": "action_actuate_front_trunk_v1_vehicles__vehicle_id__command_execution_actuate_front_trunk_post",
        "security": [{ "OAuth2ClientCredentialsBearer": ["vehicle:commands"] }]
      }
    },
    "/v1/vehicles/{vehicle_id}/command-execution:actuate-rear-trunk": {
      "post": {
        "tags": ["Vehicle Command Executions"],
        "summary": "Action Actuate Rear Trunk",
        "description": "Create a `ACTUATE_REAR_TRUNK` command execution.",
        "operationId": "action_actuate_rear_trunk_v1_vehicles__vehicle_id__command_execution_actuate_rear_trunk_post",
        "security": [{ "OAuth2ClientCredentialsBearer": ["vehicle:commands"] }]
      }
    },
    "/v1/vehicles/{vehicle_id}/command-execution:climate-off": {
      "post": {
        "tags": ["Vehicle Command Executions"],
        "summary": "Action Climate Off",
        "description": "Create a `CLIMATE_OFF` command execution.",
        "operationId": "action_climate_off_v1_vehicles__vehicle_id__command_execution_climate_off_post",
        "security": [{ "OAuth2ClientCredentialsBearer": ["vehicle:commands"] }]
      }
    },
    "/v1/vehicles/{vehicle_id}/command-execution:climate-on": {
      "post": {
        "tags": ["Vehicle Command Executions"],
        "summary": "Action Climate On",
        "description": "Create a `CLIMATE_ON` command execution.",
        "operationId": "action_climate_on_v1_vehicles__vehicle_id__command_execution_climate_on_post",
        "security": [{ "OAuth2ClientCredentialsBearer": ["vehicle:commands"] }]
      }
    },
    "/v1/vehicles/{vehicle_id}/command-execution:close-charge-port": {
      "post": {
        "tags": ["Vehicle Command Executions"],
        "summary": "Action Close Charge Port",
        "description": "Create a `CLOSE_CHARGE_PORT` command execution.",
        "operationId": "action_close_charge_port_v1_vehicles__vehicle_id__command_execution_close_charge_port_post",
        "security": [{ "OAuth2ClientCredentialsBearer": ["vehicle:commands"] }]
      }
    },
    "/v1/vehicles/{vehicle_id}/command-execution:lock-doors": {
      "post": {
        "tags": ["Vehicle Command Executions"],
        "summary": "Action Lock Doors",
        "description": "Create a `LOCK_DOORS` command execution.",
        "operationId": "action_lock_doors_v1_vehicles__vehicle_id__command_execution_lock_doors_post",
        "security": [{ "OAuth2ClientCredentialsBearer": ["vehicle:commands"] }]
      }
    },
    "/v1/vehicles/{vehicle_id}/command-execution:open-charge-port": {
      "post": {
        "tags": ["Vehicle Command Executions"],
        "summary": "Action Open Charge Port",
        "description": "Create a `OPEN_CHARGE_PORT` command execution.",
        "operationId": "action_open_charge_port_v1_vehicles__vehicle_id__command_execution_open_charge_port_post",
        "security": [{ "OAuth2ClientCredentialsBearer": ["vehicle:commands"] }]
      }
    },
    "/v1/vehicles/{vehicle_id}/command-execution:set-charge-limit": {
      "post": {
        "tags": ["Vehicle Command Executions"],
        "summary": "Action Set Charge Limit",
        "description": "Create a `SET_CHARGE_LIMIT` command execution.",
        "operationId": "action_set_charge_limit_v1_vehicles__vehicle_id__command_execution_set_charge_limit_post",
        "security": [{ "OAuth2ClientCredentialsBearer": ["vehicle:commands"] }]
      }
    },
    "/v1/vehicles/{vehicle_id}/command-execution:set-temperature": {
      "post": {
        "tags": ["Vehicle Command Executions"],
        "summary": "Action Set Temperature",
        "description": "Create a `SET_TEMPERATURE` command execution.",
        "operationId": "action_set_temperature_v1_vehicles__vehicle_id__command_execution_set_temperature_post",
        "security": [{ "OAuth2ClientCredentialsBearer": ["vehicle:commands"] }]
      }
    },
    "/v1/vehicles/{vehicle_id}/command-execution:start-charging": {
      "post": {
        "tags": ["Vehicle Command Executions"],
        "summary": "Action Start Charging",
        "description": "Create a `START_CHARGING` command execution.",
        "operationId": "action_start_charging_v1_vehicles__vehicle_id__command_execution_start_charging_post",
        "security": [{ "OAuth2ClientCredentialsBearer": ["vehicle:commands"] }]
      }
    },
    "/v1/vehicles/{vehicle_id}/command-execution:start-hvac-system": {
      "post": {
        "tags": ["Vehicle Command Executions"],
        "summary": "Action Start Hvac System",
        "description": "Create a `START_HVAC_SYSTEM` command execution.",
        "operationId": "action_start_hvac_system_v1_vehicles__vehicle_id__command_execution_start_hvac_system_post",
        "security": [{ "OAuth2ClientCredentialsBearer": ["vehicle:commands"] }]
      }
    },
    "/v1/vehicles/{vehicle_id}/command-execution:stop-charging": {
      "post": {
        "tags": ["Vehicle Command Executions"],
        "summary": "Action Stop Charging",
        "description": "Create a `STOP_CHARGING` command execution.",
        "operationId": "action_stop_charging_v1_vehicles__vehicle_id__command_execution_stop_charging_post",
        "security": [{ "OAuth2ClientCredentialsBearer": ["vehicle:commands"] }]
      }
    },
    "/v1/vehicles/{vehicle_id}/command-execution:unlock-doors": {
      "post": {
        "tags": ["Vehicle Command Executions"],
        "summary": "Action Unlock Doors",
        "description": "Create a `UNLOCK_DOORS` command execution.",
        "operationId": "action_unlock_doors_v1_vehicles__vehicle_id__command_execution_unlock_doors_post",
        "security": [{ "OAuth2ClientCredentialsBearer": ["vehicle:commands"] }]
      }
    },
    "/v1/vehicles/{vehicle_id}/charging-history": {
      "get": {
        "tags": ["Vehicle Charging History"],
        "summary": "List Vehicle Charging History",
        "description": "List Vehicle Charging History\n\nRetrieve a list of charging history sessions for the provided vehicle.\n\nParameters:\n    - `vehicle_id`: The unique identifier (ID) of the vehicle to retrieve charging history for.\n\nReturns:\n    - A paginated list of vehicle charging history sessions.\n\nThis endpoint allows you to retrieve a paginated list of charging history sessions for a specific vehicle identified by its unique `vehicle_id`.\nThe list is ordered by the starting t[...]",
        "operationId": "list_vehicle_charging_history_v1_vehicles__vehicle_id__charging_history_get",
        "security": [
          { "OAuth2ClientCredentialsBearer": [] },
          { "OAuth2ClientCredentialsBearer": ["vehicle:charging_history"] }
        ]
      }
    },
    "/v1/vehicles/{vehicle_id}/charging-history/{vehicle_charging_session_id}": {
      "get": {
        "tags": ["Vehicle Charging History"],
        "summary": "Get Vehicle Charging History",
        "description": "Retrieve Vehicle Charging Session\n\nRetrieve details of a vehicle charging session based on its unique ID.\n\nParameters:\n    - `vehicle_id`: The unique identifier (ID) of the vehicle associated with the charging session.\n    - `vehicle_charging_session_id`: The unique identifier (ID) of the vehicle charging session to retrieve.\n\nReturns:\n    - Details of the vehicle charging session.\n\nThis endpoint allows you to retrieve details of a specific vehicle charging ses[...]",
        "operationId": "get_vehicle_charging_history_v1_vehicles__vehicle_id__charging_history__vehicle_charging_session_id__get",
        "security": [
          { "OAuth2ClientCredentialsBearer": [] },
          { "OAuth2ClientCredentialsBearer": ["vehicle:charging_history"] }
        ]
      }
    },
    "/v1/bess/single/{bess_id}/telemetry": {
      "get": {
        "tags": ["BESS Telemetry"],
        "summary": "Bess Single Telemetry",
        "description": "BESS Single Telemetry Endpoint\n\nNote: The BESS-related endpoints are currently in **beta** and are expected to be fully rolled out soon\n\nThis endpoint provides detailed telemetry information for a specific BESS unit\nbased on the specified parameters.\n\n**Parameters**:\n- `bess_id`: Volteras' unique identifier for the BESS unit\n\n**Returns**:\n- `BessSingle`: A response object containing the telemetry data with identifiers, energy metrics,\nstate of charge, and othe[...]",
        "operationId": "bess_single_telemetry_v1_bess_single__bess_id__telemetry_get"
      }
    },
    "/v1/bess/aggregate/{system_id}/telemetry": {
      "get": {
        "tags": ["BESS Telemetry"],
        "summary": "Bess Aggregate Telemetry",
        "description": "BESS Aggregate Telemetry Endpoint\n\nNote: The BESS-related endpoints are currently in **beta** and are expected to be fully rolled out soon\n\nRetrieve telemetry data for a specific BESS (Battery Energy Storage System) system.\n\nThis endpoint provides detailed telemetry data for a BESS system. This encompasses\nthe system's energy metrics, energy flow metrics, and relevant metadata. The telemetry\ndata presented is an aggregate representation, often used for comprehensi[...]",
        "operationId": "bess_aggregate_telemetry_v1_bess_aggregate__system_id__telemetry_get"
      }
    }
  },
  "components": {
    "securitySchemes": {
      "OAuth2ClientCredentialsBearer": {
        "type": "oauth2",
        "flows": {
          "clientCredentials": { "scopes": {}, "tokenUrl": "/v1/oauth2/token" }
        }
      }
    }
  }
}
